######################################################################
# File: PB.icf.inputFile.dsc
#
# In dit bestand wordt de indeling van de data records voor de
# MRDF gedefinieerd.
#
# versie    Datum   Auteur         Omschrijving
#  0.1   11-07-2013 Wouter Brouwer Eerste versie
#
######################################################################
JobFiller,character,2
JobID,character,8,[expr=Job.Inserter.JobID]
PieceID,integer,6,[expr=Doc.Insert.RecipientName]
JobType,character,32
SourceID,character,32
TotalSheetsInputFdr1,integer,5,[expr=Doc.OriginalSheets]
TotalSheetsInputFdr2,integer,5
TotalSheetsInputFdr3,integer,5
TotalSheetsInputFdr4,integer,5
SubsetInput01,integer,5
SubsetInput02,integer,5
SubsetInput03,integer,5
SubsetInput04,integer,5
StitchInput01,integer,5
StitchInput02,integer,5
StitchInput03,integer,5
StitchInput04,integer,5
InputWeight,character,5,[expr="0.000"]
InsertFeeder01_06,integer,6,[expr=if(defined(Doc.Insert.BinTriggers),Doc.Insert.BinTriggers,0)]
InsertFeeder07_16,integer,10
AccountPull,integer,1
QualityAudit,integer,1,[expr=SUBSTR(Doc.Insert.DivertBin,2,1)]
AlertClear,integer,1
EdgeMarker,integer,1,[expr=SUBSTR(Doc.Insert.DivertBin,1,1)]
VS1,integer,1
VS2,integer,1
VS3,integer,1
VS4,integer,1
VS5,integer,1
VS6,integer,1
AccountIdentifier1,character,40
AccountIdentifier2,character,40
AccountIdentifier3,character,40
AccountIdentifier4,character,40
RecipientName,character,40
RecipientAddress1,character,40
RecipientAddress2,character,40
RecipientAddress3,character,40
RecipientAddress4,character,40
RecipientAddress5,character,40
RecipientAddress6,character,40
Zip,character,16
ZipShort,character,16
BusinessReturnAddress1,character,40
BusinessReturnAddress2,character,40
BusinessReturnAddress3,character,40
BusinessReturnAddress4,character,40
BusinessReturnAddress5,character,40
ReprintIndex,character,30,[expr=fmt("%i",Doc.ID)]
ReprintStartPageOffset,integer,6
ReprintPageCountOffset,integer,6
SSCCode,character,10
TraybackKick,character,1
UniqueTraybackNumber,character,20
Spare,character,9
ClientJobID,character,40
ClientDocID,character,8
CameoCode,integer,2
LogoSelect,integer,1
TranspromoSelect,integer,1
PPMLang,character,2
PPMLogo,character,20
PPMTiff,character,20
PPMIndicia,character,20
Filler,character,60
